name: $(Date:yyMMdd)$(rev:-r)

trigger:
  batch: true
  branches:
    include:
      - master
      - release/*
  paths:
    include:
      - projects

resources:
  repositories:
  - repository: devops
    type: git
    name: devops
# https://developercommunity.visualstudio.com/t/Enable-SystemPullRequest-Variables-in/10867807
    ref: ${{ iif(and(ne(variables['Build.Reason'], 'PullRequest'), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))),
                  variables['Build.SourceBranch'], 'refs/heads/master') }}

extends:
  template: build-mobile-projects.yml@devops
  parameters:
    RepoName: self
