name: $(Date:yyMMdd)$(rev:-r)

trigger:
  batch: true
  branches:
    include:
      - master
      - release/*
  paths:
    include:
      - projects
      - config.*
  tags:
    include:
      - "*"

pool:
  vmImage: ubuntu-latest

jobs:
- job: build_mobile_projects
  displayName: Build Mobile Projects
  steps:
  - checkout: self
    fetchDepth: 1

  - bash: |
      find projects -mindepth 1 -maxdepth 1 -type d -print0 | while read -d $'\0' dir; do
        name=$(basename "$dir")
        project=$(grep "displayname=\"$name\"" config.xml | sed 's/.* url="\(.*\)".*/\1/g')
        [[ ! $project ]] && echo Unknown project: $name && exit 1
        echo $name: $project
        pushd "$dir"
        zip -q -r ../data.zip *
        mkdir -p "$(Build.ArtifactStagingDirectory)/$(dirname $project)"
        echo -e -n '<?xml version="1.0" encoding="utf-8"?>\n<data xmlns="https://schema.resco.net/mobilecrm/woodford/config/data">' > "$(Build.ArtifactStagingDirectory)/$project"
        base64 -w 0 ../data.zip >> "$(Build.ArtifactStagingDirectory)/$project"
        echo '</data>' >> "$(Build.ArtifactStagingDirectory)/$project"
        rm ../data.zip
        popd
      done
      cp -v config.* $(Build.ArtifactStagingDirectory)
    displayName: Prepare Mobile Projects

  - publish: $(Build.ArtifactStagingDirectory)
    displayName: Publish Artifact
    enabled: ${{ ne(variables['Build.Reason'], 'PullRequest') }}
    artifact: mobile-projects

  - bash: |
      if [[ $(Build.SourceBranch) == refs/tags/* ]]; then
        version=$(echo $(Build.SourceBranch) | cut -d / -f 3)
        owner="Release $version"
      else
        branch=$(echo $(Build.SourceBranch) | cut -d / -f 3-)
        owner="Branch $branch"
      fi
      PAT=$(echo -n :$(System.AccessToken) | base64 -w 0)
      URL=$(System.CollectionUri)$(System.TeamProject)/_apis/build/retention/leases?api-version=6.0-preview.1
      curl -H "Content-Type: application/json" -H "Authorization: Basic $PAT" $URL --data "[{'daysValid': 90, 'definitionId': $(System.DefinitionId), 'ownerId': 'RM: $owner', 'protectPipeline': false, 'runId': $(Build.BuildId)}]"
    displayName: Lease Build
    enabled: ${{ eq(variables['Build.Reason'], 'BatchedCI') }}
