name: $(Date:yyMMdd)$(rev:-r)

trigger: none

pr: none

lockBehavior: sequential

resources:
  pipelines:
  - pipeline: mobileprojects
    source: Resco Solutions CI
    trigger:
      branches:
        include:
          - master
          - release/*

  - pipeline: webprojects
    source: Web Projects Dynamics

  - pipeline: pcfs
    source: Web Projects CI

  repositories:
  - repository: devops
    type: git
    name: devops
    ref: ${{ variables['Build.SourceBranch'] }}

  - repository: dynamics
    type: git
    name: woodford-dynamics
    ref: ${{ variables['Build.SourceBranch'] }}

parameters:
- name: LatestMobileProjects
  type: boolean
  default: true
  displayName: Use the latest mobile projects artifact

- name: LatestWebProjects
  type: boolean
  default: true
  displayName: Use the latest web projects artifacts

- name: LatestQuestionnaire
  type: boolean
  default: true
  displayName: Use the latest questionnaire artifact

extends:
  template: build-dynamics-solutions.yml@devops
  parameters:
    RepoName: dynamics
    MobileProjectsRunVersion: ${{ iif(parameters.LatestMobileProjects, 'latestFromBranch', 'specific') }}
    WebProjectsRunVersion: ${{ iif(parameters.LatestWebProjects, 'latestFromBranch', 'specific') }}
    QuestionnaireRunVersion: ${{ iif(parameters.LatestQuestionnaire, 'latestFromBranch', 'specific') }}
